# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:8

stages:
  - test
  - build
  - deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - client/node_modules/

before_script:
  # Install ssh-agent if not already installed, it is required by Docker.
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)
  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  # Check the server's host key
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'


test:
  stage: test
  script: echo "You should run some tests here!"

build:
  stage: build
  script:
    - apt-get update
    - apt-get install apt-transport-https
    - 'curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -'
    - 'echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list'
    - apt-get update
    - apt-get install -y yarn
    - cd client
    - yarn
    - yarn run build
  artifacts:
    paths:
      - client/build/

deploy:
  stage: deploy
  only: 
      - master
  when: manual
  environment:
    name: production
    url: https://progress-clocks.commandertso.com
  script:
    - scp -P22 -r client/build/* gitlab@progress-clocks.commandertso.com:/var/www/html/progress-clocks.commandertso.com/public_html

      
